
version: 2

models:
  - name: neighbourhoods_table_dim
    description: "Euskadi's neighbourhood table"
    columns:
      - name: id
        description: "primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: neighbourhood_group
        description: "neighbourhood group in euskadi"
        data_tests:
          - not_null
      - name: neighbourhood
        description: "neighbourhood in euskadi"
        data_tests:
          - unique
          - not_null

          
