airbnb_euskadi:
  outputs:
    dev:
      dataset: airbnb_euskadi
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/airflow/keys/credentials.json
      location: asia-southeast2
      method: service-account
      priority: interactive
      project: dbt-icanooo
      threads: 1
      type: bigquery
  target: dev